version: '3.8'

services:
  db:
    image: postgres:16.9-alpine
    env_file:
      - ./.env
    volumes:
       - /var/lib/postgresql/data/
  web:
    build: .
    restart: always
    expose: 
      - '8000'
    depends_on:
      - db
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
    env_file:
      - ./.env
  nginx:
    image: nginx:1.24
    ports:
      - '80:80'
    depends_on:
      - web
    volumes:
      - static_volume:/app/static/
      - media_volume:/app/media/
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

    
volumes:
  static_volume:
  media_volume:

