# Generated by Django 5.1.7 on 2025-05-30 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_tagpost_post_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posttag',
            old_name='tag',
            new_name='tags',
        ),
    ]
