# Generated by Django 5.1.7 on 2025-06-19 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_likes_delete_followers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
