# Generated by Django 5.2 on 2025-04-24 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
