# Generated by Django 5.2 on 2025-05-04 10:26

import posts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=100, validators=[posts.validators.validate_not_empty]),
        ),
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(max_length=200, validators=[posts.validators.validate_not_empty]),
        ),
    ]
