# Generated by Django 5.1.7 on 2025-05-09 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_book_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
    ]
