# Generated by Django 5.1.7 on 2025-05-09 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_book_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
