# Generated by Django 5.1.7 on 2025-05-09 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_remove_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='image',
        ),
    ]
