# Generated by Django 5.1.7 on 2025-05-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default=2, help_text='Загрузите картинку', upload_to='yatube/', verbose_name='Картинка'),
            preserve_default=False,
        ),
    ]
