# Generated by Django 5.1.7 on 2025-05-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(help_text='Загрузите картинку', upload_to='media/yatube/', verbose_name='Картинка'),
        ),
    ]
