# Generated by Django 5.1.7 on 2025-05-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_alter_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, help_text='Upload your image if you want', null=True, upload_to='yatube/', verbose_name='Img'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(help_text='Загрузите картинку', upload_to='yatube/', verbose_name='Картинка'),
        ),
    ]
