# Generated by Django 5.1.7 on 2025-05-12 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0026_rename_post_comment_ppost_post_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='pPost',
            new_name='post',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Comment',
        ),
    ]
