# Generated by Django 5.1.7 on 2025-04-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.CharField(default=2, max_length=40),
            preserve_default=False,
        ),
    ]
