# Generated by Django 5.2 on 2025-04-24 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_name_users_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='first_name',
            new_name='name',
        ),
    ]
