# Generated by Django 5.2 on 2025-05-04 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_group_usersinformation_delete_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersinformation',
            old_name='suceond_name',
            new_name='second_name',
        ),
    ]
