# Generated by Django 5.2 on 2025-05-04 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_suceond_name_usersinformation_second_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersinformation',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.group'),
        ),
    ]
