# Generated by Django 5.1.7 on 2025-05-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_usersinformation_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='about_slug',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='usersinformation',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='usersinformation',
            name='second_name',
            field=models.CharField(max_length=20),
        ),
    ]
